### ISSUE TITLE
heredoc prefix <<- is different than HCL spec

### ISSUE THREAD

**Issue by tbugfinder** [mfcastellani/hcl-checker#3]
https://github.com/mfcastellani/hcl-checker/blob/master/lib/hcl/lexer.rb#L84

`<<-` is not a requirement by HCL
If heredoc starts with `<<-HEREDOC` then `terraform fmt` expects ending with `-HEREDOC` instead of `HEREDOC`.

**Comment by kcburge** [comment]
This is addressed by #6
